context:
  version: "0.10.1"

package:
  name: gurk
  version: ${{ version }}

source:
  url: https://github.com/boxdot/gurk-rs/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b2154a45b8ab89f48d71451f128f0888e1107745ede943e510885f9026241567

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      OPENSSL_NO_VENDOR: "1"
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # NOTE: we force using the host's (conda-forge's) OpenSSL lib dir for the `libsqlite3-sys` dependency unless on macOS where the OS' native Security Framework is used instead 
      - if: not osx
        then: $env.OPENSSL_DIR = ($prefix)
      # build main app and generate license data
      - cargo auditable install --path=. --root=($prefix) --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - cargo-auditable
    - cargo-bundle-licenses
    - libprotobuf
    - nushell
    - perl
    - pkg-config
  host:
    - if: not osx
      then: openssl

tests:
  - script:
      - gurk --help
      - gurk --version
  - package_contents:
      bin:
        - gurk
      strict: true

about:
  summary: Signal Messenger client for the terminal
  description: |
    gurk is a Signal Messenger client for the terminal, built in Rust as a
    text-based user interface (TUI) application on top of the unofficial
    `presage` Signal library.
  license: AGPL-3.0-only
  license_file:
    - LICENSE-AGPL-3.0
    - THIRDPARTY.yml
  homepage: https://github.com/boxdot/gurk-rs
  repository: https://github.com/boxdot/gurk-rs

extra:
  recipe-maintainers:
    - salim-b
